package br.com.brunotonia.supertrunfo.vo;
// Generated 02/11/2016 21:46:38 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carro generated by hbm2java
 */
@Entity
@Table(name = "carro", schema = "public")
public class Carro implements java.io.Serializable {

    private Long id;
    private Integer ano;
    private Integer cc;
    private Integer cilindros;
    private String fabricante;
    private String imagem;
    private String nome;
    private String pais;
    private BigDecimal peso;
    private BigDecimal potencia;
    private BigDecimal vmax;

    public Carro() {
    }

    public Carro(Integer ano, Integer cc, Integer cilindros, String fabricante, String imagem, String nome, String pais, BigDecimal peso, BigDecimal potencia, BigDecimal vmax) {
        this.ano = ano;
        this.cc = cc;
        this.cilindros = cilindros;
        this.fabricante = fabricante;
        this.imagem = imagem;
        this.nome = nome;
        this.pais = pais;
        this.peso = peso;
        this.potencia = potencia;
        this.vmax = vmax;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "ano", nullable = false)
    public Integer getAno() {
        return this.ano;
    }

    public void setAno(Integer ano) {
        this.ano = ano;
    }

    @Column(name = "cc", nullable = false)
    public Integer getCc() {
        return this.cc;
    }

    public void setCc(Integer cc) {
        this.cc = cc;
    }

    @Column(name = "cilindros", nullable = false)
    public Integer getCilindros() {
        return this.cilindros;
    }

    public void setCilindros(Integer cilindros) {
        this.cilindros = cilindros;
    }

    @Column(name = "fabricante", nullable = false, length = 30)
    public String getFabricante() {
        return this.fabricante;
    }

    public void setFabricante(String fabricante) {
        this.fabricante = fabricante;
    }

    @Column(name = "imagem", nullable = false)
    public String getImagem() {
        return this.imagem;
    }

    public void setImagem(String imagem) {
        this.imagem = imagem;
    }

    @Column(name = "nome", nullable = false, length = 30)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "pais", nullable = false, length = 30)
    public String getPais() {
        return this.pais;
    }

    public void setPais(String pais) {
        this.pais = pais;
    }

    @Column(name = "peso", nullable = false, precision = 131089, scale = 0)
    public BigDecimal getPeso() {
        return this.peso;
    }

    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }

    @Column(name = "potencia", nullable = false, precision = 131089, scale = 0)
    public BigDecimal getPotencia() {
        return this.potencia;
    }

    public void setPotencia(BigDecimal potencia) {
        this.potencia = potencia;
    }

    @Column(name = "vmax", nullable = false, precision = 131089, scale = 0)
    public BigDecimal getVmax() {
        return this.vmax;
    }

    public void setVmax(BigDecimal vmax) {
        this.vmax = vmax;
    }

}
